# Generated by Django 4.2.2 on 2023-06-24 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_fruit_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='web.profile'),
            preserve_default=False,
        ),
    ]
